import 'bloc/interiorcar_bloc.dart';import 'models/interiorcar_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/core/utils/validation_functions.dart';import 'package:indus_motors/widgets/app_bar/appbar_leading_image.dart';import 'package:indus_motors/widgets/app_bar/appbar_title.dart';import 'package:indus_motors/widgets/app_bar/appbar_trailing_image.dart';import 'package:indus_motors/widgets/app_bar/custom_app_bar.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';import 'package:indus_motors/widgets/custom_icon_button.dart';import 'package:indus_motors/widgets/custom_outlined_button.dart';import 'package:indus_motors/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class InteriorcarScreen extends StatelessWidget {InteriorcarScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<InteriorcarBloc>(create: (context) => InteriorcarBloc(InteriorcarState(interiorcarModelObj: InteriorcarModel()))..add(InteriorcarInitialEvent()), child: InteriorcarScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 13.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 79.h), child: Row(children: [CustomIconButton(height: 42.adaptSize, width: 42.adaptSize, onTap: () {onTapBtnIconsBackButtonThirty(context);}, child: CustomImageView(imagePath: ImageConstant.imgIcons8BackButton30)), CustomOutlinedButton(width: 161.h, text: "msg_interior_detailing2".tr, margin: EdgeInsets.only(left: 50.h, top: 4.v))])), SizedBox(height: 44.v), CustomImageView(imagePath: ImageConstant.imgFiatCentoventi096, height: 187.v, width: 292.h, radius: BorderRadius.circular(47.h), alignment: Alignment.center), SizedBox(height: 31.v), _buildNameSection(context), SizedBox(height: 16.v), _buildRegisterNumberInputSection(context), SizedBox(height: 16.v), _buildServiceTypeInputSection(context), SizedBox(height: 25.v), CustomElevatedButton(width: 131.h, text: "lbl_submit".tr, margin: EdgeInsets.only(right: 89.h), buttonStyle: CustomButtonStyles.fillRed1, onPressed: () {onTapSUBMIT(context);}, alignment: Alignment.centerRight), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgHome, margin: EdgeInsets.only(left: 30.h, top: 45.v, bottom: 32.v)), centerTitle: true, title: AppbarTitle(text: "lbl_indus_motors2".tr, margin: EdgeInsets.only(top: 49.v, bottom: 25.v)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgEllipse15, margin: EdgeInsets.fromLTRB(19.h, 30.v, 19.h, 31.v))], styleType: Style.bgStyle_16); } 
/// Section Widget
Widget _buildNameSection(BuildContext context) { return Container(margin: EdgeInsets.only(right: 20.h), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 34.h), child: Text("lbl_car_model".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 16.h), child: BlocSelector<InteriorcarBloc, InteriorcarState, TextEditingController?>(selector: (state) => state.nameController, builder: (context, nameController) {return CustomTextFormField(controller: nameController, hintText: "msg_enter_your_car_name".tr, alignment: Alignment.centerRight, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}))])); } 
/// Section Widget
Widget _buildRegisterNumberInputSection(BuildContext context) { return Container(margin: EdgeInsets.only(right: 20.h), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 34.h), child: Text("lbl_register_no".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 16.h), child: BlocSelector<InteriorcarBloc, InteriorcarState, TextEditingController?>(selector: (state) => state.registerNumberInputController, builder: (context, registerNumberInputController) {return CustomTextFormField(controller: registerNumberInputController, hintText: "msg_enter_your_register".tr, textInputType: TextInputType.number, alignment: Alignment.centerRight, validator: (value) {if (!isNumeric(value)) {return "err_msg_please_enter_valid_number".tr;} return null;});}))])); } 
/// Section Widget
Widget _buildServiceTypeInputSection(BuildContext context) { return Container(margin: EdgeInsets.only(right: 20.h), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 37.h), child: Text("lbl_type_of_service".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 16.h), child: BlocSelector<InteriorcarBloc, InteriorcarState, TextEditingController?>(selector: (state) => state.serviceTypeInputController, builder: (context, serviceTypeInputController) {return CustomTextFormField(controller: serviceTypeInputController, hintText: "lbl_type_here".tr, textInputAction: TextInputAction.done, alignment: Alignment.centerRight);}))])); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapBtnIconsBackButtonThirty(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
/// Navigates to the submittedsuccessfullyScreen when the action is triggered.
onTapSUBMIT(BuildContext context) { NavigatorService.pushNamed(AppRoutes.submittedsuccessfullyScreen, ); } 
 }
