import '../homemain_page/widgets/buttongrid_item_widget.dart';import 'bloc/homemain_bloc.dart';import 'models/buttongrid_item_model.dart';import 'models/homemain_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';class HomemainPage extends StatefulWidget {const HomemainPage({Key? key}) : super(key: key);

@override HomemainPageState createState() =>  HomemainPageState();

static Widget builder(BuildContext context) { return BlocProvider<HomemainBloc>(create: (context) => HomemainBloc(HomemainState(homemainModelObj: HomemainModel()))..add(HomemainInitialEvent()), child: HomemainPage()); } 
 }
class HomemainPageState extends State<HomemainPage> with  AutomaticKeepAliveClientMixin<HomemainPage> {@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 5.v), Column(children: [CustomImageView(imagePath: ImageConstant.img167120221103194331, height: 114.v, width: 360.h), SizedBox(height: 6.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 17.h), child: Text("msg_top_selling_cars".tr, style: CustomTextStyles.titleSmallBlack90015))), SizedBox(height: 28.v), SizedBox(height: 1018.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.centerLeft, child: Container(margin: EdgeInsets.only(left: 16.h), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 7.v), decoration: AppDecoration.outlineBlack, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_ciaz".tr, style: theme.textTheme.labelLarge)), SizedBox(height: 2.v), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_price_starts".tr, style: theme.textTheme.bodySmall)), SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(left: 7.h), child: Text("lbl_9_30_lac".tr, style: CustomTextStyles.titleLargeOnError)), SizedBox(height: 9.v), CustomImageView(imagePath: ImageConstant.imgRectangle121, height: 56.v, width: 91.h, radius: BorderRadius.circular(11.h), alignment: Alignment.center), SizedBox(height: 14.v), _buildFindOutMoreButton1(context)]))), Align(alignment: Alignment.bottomLeft, child: Container(margin: EdgeInsets.only(left: 16.h, bottom: 213.v), padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.outlineBlack, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), Padding(padding: EdgeInsets.only(left: 13.h), child: Text("lbl_celerio".tr, style: theme.textTheme.labelLarge)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 13.h), child: Text("lbl_price_starts".tr, style: theme.textTheme.bodySmall)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_5_37_lac".tr, style: CustomTextStyles.titleLargeOnError)), SizedBox(height: 14.v), CustomImageView(imagePath: ImageConstant.imgRectangle124, height: 46.v, width: 75.h, radius: BorderRadius.circular(11.h), margin: EdgeInsets.only(left: 19.h)), SizedBox(height: 21.v), _buildFindOutMoreButton2(context)]))), _buildHomeRow(context), _buildButtonGrid(context)])), SizedBox(height: 42.v), _buildPopularModelsColumn(context)])]))))); } 
/// Section Widget
Widget _buildFindOutMoreButton1(BuildContext context) { return CustomElevatedButton(height: 25.v, width: 136.h, text: "lbl_find_out_more".tr, margin: EdgeInsets.only(left: 3.h), buttonStyle: CustomButtonStyles.fillBlueGray, buttonTextStyle: CustomTextStyles.bodyMediumBlack900Light); } 
/// Section Widget
Widget _buildFindOutMoreButton2(BuildContext context) { return CustomElevatedButton(height: 25.v, width: 136.h, text: "lbl_find_out_more".tr, buttonStyle: CustomButtonStyles.fillBlueGray, buttonTextStyle: CustomTextStyles.bodyMediumBlack900Light, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildHomeRow(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 402.v, bottom: 516.v), padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 33.v), decoration: AppDecoration.fillRed, child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 8.h, top: 12.v), child: Text("lbl_home".tr, style: CustomTextStyles.bodyLargeWhiteA700)), Spacer(), GestureDetector(onTap: () {onTapTxtFEEDBACK(context);}, child: Padding(padding: EdgeInsets.only(top: 10.v), child: Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeRegular))), GestureDetector(onTap: () {onTapTxtSERVICES(context);}, child: Padding(padding: EdgeInsets.only(left: 30.h, top: 10.v), child: Text("lbl_services".tr, style: CustomTextStyles.bodyLargeRegular)))]))); } 
/// Section Widget
Widget _buildButtonGrid(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 17.h), child: BlocSelector<HomemainBloc, HomemainState, HomemainModel?>(selector: (state) => state.homemainModelObj, builder: (context, homemainModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 184.v, crossAxisCount: 2, mainAxisSpacing: 27.h, crossAxisSpacing: 27.h), physics: BouncingScrollPhysics(), itemCount: homemainModelObj?.buttongridItemList.length ?? 0, itemBuilder: (context, index) {ButtongridItemModel model = homemainModelObj?.buttongridItemList[index] ?? ButtongridItemModel(); return ButtongridItemWidget(model);});}))); } 
/// Section Widget
Widget _buildPopularModelsColumn(BuildContext context) { return Container(width: 325.h, margin: EdgeInsets.symmetric(horizontal: 17.h), padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 13.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_popular_models".tr, style: CustomTextStyles.bodyMediumRegular), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 38.h), child: Row(children: [Text("lbl_jimny".tr, style: CustomTextStyles.bodySmall11), Padding(padding: EdgeInsets.only(left: 63.h), child: Text("lbl_invicto".tr, style: CustomTextStyles.bodySmall11))])), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 39.h), child: Row(children: [Text("lbl_s_presso".tr, style: CustomTextStyles.bodySmall11), Padding(padding: EdgeInsets.only(left: 38.h), child: Text("lbl_fronx".tr, style: CustomTextStyles.bodySmall11))])), SizedBox(height: 32.v), Padding(padding: EdgeInsets.only(left: 39.h), child: Text("lbl_alto".tr, style: CustomTextStyles.bodySmall11)), SizedBox(height: 9.v)])); } 
/// Navigates to the feedbacksuggestionScreen when the action is triggered.
onTapTxtFEEDBACK(BuildContext context) { NavigatorService.pushNamed(AppRoutes.feedbacksuggestionScreen, ); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapTxtSERVICES(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
 }
