import 'bloc/ciaz_bloc.dart';import 'models/ciaz_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';class CiazPage extends StatefulWidget {const CiazPage({Key? key}) : super(key: key);

@override CiazPageState createState() =>  CiazPageState();

static Widget builder(BuildContext context) { return BlocProvider<CiazBloc>(create: (context) => CiazBloc(CiazState(ciazModelObj: CiazModel()))..add(CiazInitialEvent()), child: CiazPage()); } 
 }
class CiazPageState extends State<CiazPage> with  AutomaticKeepAliveClientMixin<CiazPage> {@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return BlocBuilder<CiazBloc, CiazState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, decoration: AppDecoration.fillWhiteA, child: Column(children: [SizedBox(height: 17.v), Column(children: [_buildBackButton(context), SizedBox(height: 49.v), _buildHomeRow(context)])]))));}); } 
/// Section Widget
Widget _buildBackButton(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 22.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 25.v, width: 71.h, text: "lbl_back".tr, margin: EdgeInsets.only(left: 6.h), buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular), SizedBox(height: 20.v), Card(clipBehavior: Clip.antiAlias, elevation: 0, shape: RoundedRectangleBorder(side: BorderSide(color: appTheme.blueGray100, width: 2.h), borderRadius: BorderRadiusStyle.roundedBorder25), child: Container(height: 463.v, width: 315.h, padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 5.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgRectangle121, height: 123.v, width: 215.h, radius: BorderRadius.circular(11.h), alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 80.v)), Align(alignment: Alignment.centerLeft, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("lbl_ciaz".tr, style: CustomTextStyles.headlineLargeBlack900)), SizedBox(height: 199.v), SizedBox(width: 216.h, child: Text("msg_maruthi_ciaz_sigma_1_5".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleLargeBlack900)), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("msg_price_range_starts".tr, style: CustomTextStyles.bodyMediumLight15)), SizedBox(height: 10.v), Text("lbl_9_30_lac".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 49.v), CustomElevatedButton(height: 30.v, width: 137.h, text: "lbl_car_enquiry".tr, margin: EdgeInsets.only(right: 20.h), buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular_1, alignment: Alignment.centerRight)]))])))])); } 
/// Section Widget
Widget _buildHomeRow(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 39.v), decoration: AppDecoration.fillRed, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_home".tr, style: CustomTextStyles.bodyLargeWhiteA700)), Spacer(flex: 56), GestureDetector(onTap: () {onTapTxtFEEDBACK(context);}, child: Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeRegular)), Spacer(flex: 43), GestureDetector(onTap: () {onTapTxtSERVICES(context);}, child: Text("lbl_services".tr, style: CustomTextStyles.bodyLargeRegular))])); } 
/// Navigates to the feedbacksuggestionScreen when the action is triggered.
onTapTxtFEEDBACK(BuildContext context) { NavigatorService.pushNamed(AppRoutes.feedbacksuggestionScreen, ); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapTxtSERVICES(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
 }
