import 'bloc/wagnorbsfour_bloc.dart';import 'models/wagnorbsfour_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';class WagnorbsfourPage extends StatefulWidget {const WagnorbsfourPage({Key? key}) : super(key: key);

@override WagnorbsfourPageState createState() =>  WagnorbsfourPageState();

static Widget builder(BuildContext context) { return BlocProvider<WagnorbsfourBloc>(create: (context) => WagnorbsfourBloc(WagnorbsfourState(wagnorbsfourModelObj: WagnorbsfourModel()))..add(WagnorbsfourInitialEvent()), child: WagnorbsfourPage()); } 
 }
class WagnorbsfourPageState extends State<WagnorbsfourPage> with  AutomaticKeepAliveClientMixin<WagnorbsfourPage> {@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return BlocBuilder<WagnorbsfourBloc, WagnorbsfourState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, decoration: AppDecoration.fillWhiteA, child: Column(children: [SizedBox(height: 19.v), Column(children: [_buildBackButton(context), SizedBox(height: 49.v), _buildHomeSection(context)])]))));}); } 
/// Section Widget
Widget _buildBackButton(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 22.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 25.v, width: 71.h, text: "lbl_back".tr, margin: EdgeInsets.only(left: 6.h), buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular), SizedBox(height: 20.v), Container(margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 12.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 10.v), Text("lbl_wagon_r_bs_vi".tr, style: CustomTextStyles.headlineLargeBlack900), SizedBox(height: 28.v), CustomImageView(imagePath: ImageConstant.imgRectangle105, height: 123.v, width: 187.h, radius: BorderRadius.circular(11.h)), SizedBox(height: 49.v), Padding(padding: EdgeInsets.only(right: 5.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_wagon_r_lxi_1_0l".tr, style: CustomTextStyles.titleLargeBlack900)), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("msg_price_range_starts".tr, style: CustomTextStyles.bodyMediumLight15)), SizedBox(height: 10.v), Text("lbl_5_55_lac".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 49.v), CustomElevatedButton(height: 30.v, width: 137.h, text: "lbl_car_enquiry".tr, buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular_1, alignment: Alignment.center)]))]))])); } 
/// Section Widget
Widget _buildHomeSection(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 39.v), decoration: AppDecoration.fillRed, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_home".tr, style: CustomTextStyles.bodyLargeWhiteA700)), Spacer(flex: 56), GestureDetector(onTap: () {onTapTxtFEEDBACK(context);}, child: Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeRegular)), Spacer(flex: 43), GestureDetector(onTap: () {onTapTxtSERVICES(context);}, child: Text("lbl_services".tr, style: CustomTextStyles.bodyLargeRegular))])); } 
/// Navigates to the feedbacksuggestionScreen when the action is triggered.
onTapTxtFEEDBACK(BuildContext context) { NavigatorService.pushNamed(AppRoutes.feedbacksuggestionScreen, ); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapTxtSERVICES(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
 }
