import 'bloc/jimny_bloc.dart';import 'models/jimny_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';class JimnyPage extends StatefulWidget {const JimnyPage({Key? key}) : super(key: key);

@override JimnyPageState createState() =>  JimnyPageState();

static Widget builder(BuildContext context) { return BlocProvider<JimnyBloc>(create: (context) => JimnyBloc(JimnyState(jimnyModelObj: JimnyModel()))..add(JimnyInitialEvent()), child: JimnyPage()); } 
 }
class JimnyPageState extends State<JimnyPage> with  AutomaticKeepAliveClientMixin<JimnyPage> {@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return BlocBuilder<JimnyBloc, JimnyState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, decoration: AppDecoration.fillWhiteA, child: Column(children: [SizedBox(height: 17.v), Column(children: [_buildBackColumn(context), SizedBox(height: 49.v), _buildTwentyThreeRow(context)])]))));}); } 
/// Section Widget
Widget _buildBackColumn(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 22.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 25.v, width: 71.h, text: "lbl_back".tr, margin: EdgeInsets.only(left: 6.h), buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular), SizedBox(height: 20.v), Container(width: 315.h, margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 6.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 63.h), child: Text("lbl_jimny".tr, style: CustomTextStyles.headlineLargeBlack900)), SizedBox(height: 26.v), CustomImageView(imagePath: ImageConstant.imgRectangle73, height: 124.v, width: 183.h, radius: BorderRadius.circular(11.h), alignment: Alignment.center), SizedBox(height: 42.v), Container(width: 227.h, margin: EdgeInsets.only(right: 26.h), child: Text("msg_zeta_allgrip_pro".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleLargeBlack900)), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("msg_price_range_starts".tr, style: CustomTextStyles.bodyMediumLight15)), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_12_74_lac".tr, style: theme.textTheme.headlineLarge)), SizedBox(height: 49.v), CustomElevatedButton(height: 30.v, width: 137.h, text: "lbl_car_enquiry".tr, buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular_1, alignment: Alignment.center), SizedBox(height: 5.v)]))])); } 
/// Section Widget
Widget _buildTwentyThreeRow(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 39.v), decoration: AppDecoration.fillRed, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_home".tr, style: CustomTextStyles.bodyLargeWhiteA700)), Spacer(flex: 56), GestureDetector(onTap: () {onTapTxtFEEDBACK(context);}, child: Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeRegular)), Spacer(flex: 43), GestureDetector(onTap: () {onTapTxtSERVICES(context);}, child: Text("lbl_services".tr, style: CustomTextStyles.bodyLargeRegular))])); } 
/// Navigates to the feedbacksuggestionScreen when the action is triggered.
onTapTxtFEEDBACK(BuildContext context) { NavigatorService.pushNamed(AppRoutes.feedbacksuggestionScreen, ); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapTxtSERVICES(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
 }
