import 'bloc/carenquiry_bloc.dart';import 'models/carenquiry_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/core/utils/validation_functions.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';import 'package:indus_motors/widgets/custom_text_form_field.dart';class CarenquiryPage extends StatefulWidget {const CarenquiryPage({Key? key}) : super(key: key);

@override CarenquiryPageState createState() =>  CarenquiryPageState();

static Widget builder(BuildContext context) { return BlocProvider<CarenquiryBloc>(create: (context) => CarenquiryBloc(CarenquiryState(carenquiryModelObj: CarenquiryModel()))..add(CarenquiryInitialEvent()), child: CarenquiryPage()); } 
 }

// ignore_for_file: must_be_immutable
class CarenquiryPageState extends State<CarenquiryPage> with  AutomaticKeepAliveClientMixin<CarenquiryPage> {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 9.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 23.h), child: Text("lbl_car_enquiry".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 17.v), _buildMainForm(context), SizedBox(height: 45.v), CustomElevatedButton(height: 48.v, width: 93.h, text: "lbl_send".tr, margin: EdgeInsets.only(left: 56.h), rightIcon: Container(margin: EdgeInsets.only(left: 7.h), child: CustomImageView(imagePath: ImageConstant.imgIcons8back64223x24, height: 23.v, width: 24.h)), buttonStyle: CustomButtonStyles.fillRed1), SizedBox(height: 20.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 17.h), child: Text("lbl_notification".tr, style: CustomTextStyles.bodyMediumWhiteA700Light13))), SizedBox(height: 64.v), _buildNavigationRow(context)])]))))); } 
/// Section Widget
Widget _buildCarEnquiryForm(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 19.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_name".tr, style: theme.textTheme.bodySmall), SizedBox(height: 2.v), BlocSelector<CarenquiryBloc, CarenquiryState, TextEditingController?>(selector: (state) => state.nameController, builder: (context, nameController) {return CustomTextFormField(controller: nameController, hintText: "lbl_enter_your_name".tr, hintStyle: CustomTextStyles.bodySmallBlack900, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;}, contentPadding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 6.v));})])); } 
/// Section Widget
Widget _buildContactForm(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 19.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_mobile_number".tr, style: theme.textTheme.bodySmall), SizedBox(height: 2.v), BlocSelector<CarenquiryBloc, CarenquiryState, TextEditingController?>(selector: (state) => state.mobileNumberController, builder: (context, mobileNumberController) {return CustomTextFormField(controller: mobileNumberController, hintText: "lbl_mobile_number2".tr, hintStyle: CustomTextStyles.bodySmallBlack900, textInputType: TextInputType.phone, validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;}, contentPadding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 6.v));})])); } 
/// Section Widget
Widget _buildEmailForm(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 19.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_email_address".tr, style: theme.textTheme.bodySmall), SizedBox(height: 2.v), BlocSelector<CarenquiryBloc, CarenquiryState, TextEditingController?>(selector: (state) => state.emailController, builder: (context, emailController) {return CustomTextFormField(controller: emailController, hintText: "lbl_email_address2".tr, hintStyle: CustomTextStyles.bodySmallBlack900, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, contentPadding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 6.v));})])); } 
/// Section Widget
Widget _buildModelForm(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 19.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_model".tr, style: theme.textTheme.bodySmall)), SizedBox(height: 7.v), BlocSelector<CarenquiryBloc, CarenquiryState, TextEditingController?>(selector: (state) => state.outletTypeController, builder: (context, outletTypeController) {return CustomTextFormField(controller: outletTypeController, hintText: "lbl_type".tr, hintStyle: CustomTextStyles.bodySmallBlack900, contentPadding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 6.v));})])); } 
/// Section Widget
Widget _buildOutletForm(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 19.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_outlet".tr, style: theme.textTheme.bodySmall)), SizedBox(height: 7.v), BlocSelector<CarenquiryBloc, CarenquiryState, TextEditingController?>(selector: (state) => state.outletTypeController1, builder: (context, outletTypeController1) {return CustomTextFormField(controller: outletTypeController1, hintText: "lbl_type".tr, hintStyle: CustomTextStyles.bodySmallBlack900, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 6.v));})])); } 
/// Section Widget
Widget _buildMainForm(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 56.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildCarEnquiryForm(context), SizedBox(height: 20.v), _buildContactForm(context), SizedBox(height: 26.v), _buildEmailForm(context), SizedBox(height: 21.v), _buildModelForm(context), SizedBox(height: 16.v), _buildOutletForm(context)])); } 
/// Section Widget
Widget _buildNavigationRow(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 39.v), decoration: AppDecoration.fillRed, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_home".tr, style: CustomTextStyles.bodyLargeWhiteA700)), Spacer(flex: 56), GestureDetector(onTap: () {onTapTxtFEEDBACK(context);}, child: Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeRegular)), Spacer(flex: 43), GestureDetector(onTap: () {onTapTxtSERVICES(context);}, child: Text("lbl_services".tr, style: CustomTextStyles.bodyLargeRegular))])); } 
/// Navigates to the feedbacksuggestionScreen when the action is triggered.
onTapTxtFEEDBACK(BuildContext context) { NavigatorService.pushNamed(AppRoutes.feedbacksuggestionScreen, ); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapTxtSERVICES(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
 }
