import 'bloc/ertiga_bloc.dart';import 'models/ertiga_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';class ErtigaPage extends StatefulWidget {const ErtigaPage({Key? key}) : super(key: key);

@override ErtigaPageState createState() =>  ErtigaPageState();

static Widget builder(BuildContext context) { return BlocProvider<ErtigaBloc>(create: (context) => ErtigaBloc(ErtigaState(ertigaModelObj: ErtigaModel()))..add(ErtigaInitialEvent()), child: ErtigaPage()); } 
 }
class ErtigaPageState extends State<ErtigaPage> with  AutomaticKeepAliveClientMixin<ErtigaPage> {@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return BlocBuilder<ErtigaBloc, ErtigaState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, decoration: AppDecoration.fillWhiteA, child: Column(children: [SizedBox(height: 17.v), Column(children: [_buildBackColumn(context), SizedBox(height: 49.v), _buildFortySixRow(context)])]))));}); } 
/// Section Widget
Widget _buildBackColumn(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 22.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 25.v, width: 71.h, text: "lbl_back".tr, margin: EdgeInsets.only(left: 6.h), buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular), SizedBox(height: 20.v), Container(width: 315.h, margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 12.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(left: 59.h), child: Text("lbl_ertiga".tr, style: CustomTextStyles.headlineLargeBlack900)), SizedBox(height: 28.v), CustomImageView(imagePath: ImageConstant.imgRectangle103, height: 129.v, width: 182.h, radius: BorderRadius.circular(11.h), alignment: Alignment.center), SizedBox(height: 26.v), SizedBox(width: 106.h, child: Text("msg_ertiga_lxi_petrol".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleLargeBlack900)), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("msg_price_range_starts".tr, style: CustomTextStyles.bodyMediumLight15)), SizedBox(height: 10.v), Text("lbl_8_49_lac".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 49.v), CustomElevatedButton(height: 30.v, width: 137.h, text: "lbl_car_enquiry".tr, buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular_1, alignment: Alignment.center)]))])); } 
/// Section Widget
Widget _buildFortySixRow(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 39.v), decoration: AppDecoration.fillRed, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_home".tr, style: CustomTextStyles.bodyLargeWhiteA700)), Spacer(flex: 56), GestureDetector(onTap: () {onTapTxtFEEDBACK(context);}, child: Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeRegular)), Spacer(flex: 43), GestureDetector(onTap: () {onTapTxtSERVICES(context);}, child: Text("lbl_services".tr, style: CustomTextStyles.bodyLargeRegular))])); } 
/// Navigates to the feedbacksuggestionScreen when the action is triggered.
onTapTxtFEEDBACK(BuildContext context) { NavigatorService.pushNamed(AppRoutes.feedbacksuggestionScreen, ); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapTxtSERVICES(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
 }
