import 'bloc/gsperoidiccheckup_bloc.dart';import 'models/gsperoidiccheckup_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/core/utils/validation_functions.dart';import 'package:indus_motors/widgets/app_bar/appbar_leading_image.dart';import 'package:indus_motors/widgets/app_bar/appbar_title.dart';import 'package:indus_motors/widgets/app_bar/appbar_trailing_image.dart';import 'package:indus_motors/widgets/app_bar/custom_app_bar.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';import 'package:indus_motors/widgets/custom_icon_button.dart';import 'package:indus_motors/widgets/custom_outlined_button.dart';import 'package:indus_motors/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class GsperoidiccheckupScreen extends StatelessWidget {GsperoidiccheckupScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<GsperoidiccheckupBloc>(create: (context) => GsperoidiccheckupBloc(GsperoidiccheckupState(gsperoidiccheckupModelObj: GsperoidiccheckupModel()))..add(GsperoidiccheckupInitialEvent()), child: GsperoidiccheckupScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.all(11.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 86.h), child: Row(children: [CustomIconButton(height: 42.adaptSize, width: 42.adaptSize, onTap: () {onTapBtnIconsBackButtonThirty(context);}, child: CustomImageView(imagePath: ImageConstant.imgIcons8BackButton30)), CustomOutlinedButton(height: 35.v, width: 166.h, text: "lbl_general_service2".tr, margin: EdgeInsets.only(left: 44.h, top: 7.v))])), SizedBox(height: 34.v), CustomImageView(imagePath: ImageConstant.imgGeneralService, height: 201.v, width: 312.h, radius: BorderRadius.circular(41.h), alignment: Alignment.center), SizedBox(height: 17.v), _buildNameColumn(context), SizedBox(height: 16.v), _buildRegisterNumberInputColumn(context), SizedBox(height: 16.v), _buildServiceTypeValueColumn(context), SizedBox(height: 26.v), CustomElevatedButton(width: 131.h, text: "lbl_submit".tr, margin: EdgeInsets.only(left: 90.h), buttonStyle: CustomButtonStyles.fillRed1, onPressed: () {onTapSUBMIT(context);}), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgHome, margin: EdgeInsets.only(left: 30.h, top: 45.v, bottom: 32.v)), centerTitle: true, title: AppbarTitle(text: "lbl_indus_motors2".tr, margin: EdgeInsets.only(top: 49.v, bottom: 25.v)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgEllipse15, margin: EdgeInsets.fromLTRB(19.h, 30.v, 19.h, 31.v))], styleType: Style.bgStyle_14); } 
/// Section Widget
Widget _buildNameColumn(BuildContext context) { return Container(margin: EdgeInsets.only(right: 13.h), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 18.h), child: Text("lbl_car_model".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(right: 29.h), child: BlocSelector<GsperoidiccheckupBloc, GsperoidiccheckupState, TextEditingController?>(selector: (state) => state.nameController, builder: (context, nameController) {return CustomTextFormField(controller: nameController, hintText: "msg_enter_your_car_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}))])); } 
/// Section Widget
Widget _buildRegisterNumberInputColumn(BuildContext context) { return Container(margin: EdgeInsets.only(right: 13.h), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 18.h), child: Text("lbl_register_no".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(right: 29.h), child: BlocSelector<GsperoidiccheckupBloc, GsperoidiccheckupState, TextEditingController?>(selector: (state) => state.registerNumberInputController, builder: (context, registerNumberInputController) {return CustomTextFormField(controller: registerNumberInputController, hintText: "msg_enter_your_register".tr, textInputType: TextInputType.number, validator: (value) {if (!isNumeric(value)) {return "err_msg_please_enter_valid_number".tr;} return null;});}))])); } 
/// Section Widget
Widget _buildServiceTypeValueColumn(BuildContext context) { return Container(margin: EdgeInsets.only(right: 13.h), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 21.h), child: Text("lbl_type_of_service".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(right: 29.h), child: BlocSelector<GsperoidiccheckupBloc, GsperoidiccheckupState, TextEditingController?>(selector: (state) => state.serviceTypeValueController, builder: (context, serviceTypeValueController) {return CustomTextFormField(controller: serviceTypeValueController, hintText: "msg_periodic_checkup".tr, hintStyle: CustomTextStyles.bodyMediumLight_1, textInputAction: TextInputAction.done);}))])); } 
/// Navigates to the selectgnrlsrvScreen when the action is triggered.
onTapBtnIconsBackButtonThirty(BuildContext context) { NavigatorService.pushNamed(AppRoutes.selectgnrlsrvScreen, ); } 
/// Navigates to the submittedsuccessfullyScreen when the action is triggered.
onTapSUBMIT(BuildContext context) { NavigatorService.pushNamed(AppRoutes.submittedsuccessfullyScreen, ); } 
 }
