import 'bloc/servicesnotadded_bloc.dart';import 'models/servicesnotadded_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';class ServicesnotaddedScreen extends StatelessWidget {const ServicesnotaddedScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ServicesnotaddedBloc>(create: (context) => ServicesnotaddedBloc(ServicesnotaddedState(servicesnotaddedModelObj: ServicesnotaddedModel()))..add(ServicesnotaddedInitialEvent()), child: ServicesnotaddedScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<ServicesnotaddedBloc, ServicesnotaddedState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 44.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildIndusMotorsSection(context), Spacer(flex: 33), Padding(padding: EdgeInsets.only(left: 134.h), child: Text("lbl_sorry".tr, style: CustomTextStyles.headlineSmallBlack900)), SizedBox(height: 5.v), Align(alignment: Alignment.center, child: Text("msg_currently_services".tr, style: CustomTextStyles.bodyMediumLight_1)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 74.h), child: Row(children: [Text("lbl_to_get_click".tr, style: CustomTextStyles.bodyMediumLight_1), GestureDetector(onTap: () {onTapTxtSERVICEBOOKING1(context);}, child: Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_service_booking".tr, style: CustomTextStyles.bodySmallOnError)))])), Spacer(flex: 66)])), bottomNavigationBar: _buildFortyFourSection(context)));}); } 
/// Section Widget
Widget _buildIndusMotorsSection(BuildContext context) { return Column(children: [Padding(padding: EdgeInsets.only(left: 26.h, right: 13.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 18.v), child: Text("lbl_indus_motors2".tr, style: CustomTextStyles.headlineSmallPrimary)), CustomImageView(imagePath: ImageConstant.imgLogoMoteursIndus500x333, height: 42.v, width: 87.h, margin: EdgeInsets.only(bottom: 6.v))])), SizedBox(height: 19.v), Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 5.v), decoration: AppDecoration.fillPrimaryContainer, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [GestureDetector(onTap: () {onTapTxtSERVICEBOOKING(context);}, child: Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_service_booking".tr, style: CustomTextStyles.bodySmall10))), Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_car_enquiry".tr, style: CustomTextStyles.bodySmall10)), Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_alerts".tr, style: CustomTextStyles.bodySmall10)), Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_user".tr, style: CustomTextStyles.bodySmall10))]))]); } 
/// Section Widget
Widget _buildFortyFourSection(BuildContext context) { return Container(margin: EdgeInsets.only(left: 39.h, right: 22.h, bottom: 39.v), decoration: AppDecoration.fillRed, child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [Text("lbl_home".tr, style: CustomTextStyles.bodyLargeWhiteA700), Spacer(flex: 56), GestureDetector(onTap: () {onTapTxtFEEDBACK(context);}, child: Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeRegular)), Spacer(flex: 43), GestureDetector(onTap: () {onTapTxtSERVICES(context);}, child: Text("lbl_services".tr, style: CustomTextStyles.bodyLargeRegular))])); } 
/// Navigates to the servicebookingTabContainerScreen when the action is triggered.
onTapTxtSERVICEBOOKING(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicebookingTabContainerScreen, ); } 
/// Navigates to the servicebookingTabContainerScreen when the action is triggered.
onTapTxtSERVICEBOOKING1(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicebookingTabContainerScreen, ); } 
/// Navigates to the feedbacksuggestionScreen when the action is triggered.
onTapTxtFEEDBACK(BuildContext context) { NavigatorService.pushNamed(AppRoutes.feedbacksuggestionScreen, ); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapTxtSERVICES(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
 }
