import 'bloc/spresso_bloc.dart';import 'models/spresso_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';class SpressoPage extends StatefulWidget {const SpressoPage({Key? key}) : super(key: key);

@override SpressoPageState createState() =>  SpressoPageState();

static Widget builder(BuildContext context) { return BlocProvider<SpressoBloc>(create: (context) => SpressoBloc(SpressoState(spressoModelObj: SpressoModel()))..add(SpressoInitialEvent()), child: SpressoPage()); } 
 }
class SpressoPageState extends State<SpressoPage> with  AutomaticKeepAliveClientMixin<SpressoPage> {@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return BlocBuilder<SpressoBloc, SpressoState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, decoration: AppDecoration.fillWhiteA, child: Column(children: [SizedBox(height: 22.v), Column(children: [_buildBackButtonSection(context), SizedBox(height: 49.v), _buildHomeSection(context)])]))));}); } 
/// Section Widget
Widget _buildBackButtonSection(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 22.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 25.v, width: 71.h, text: "lbl_back".tr, margin: EdgeInsets.only(left: 6.h), buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular), SizedBox(height: 20.v), Container(width: 315.h, margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 6.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("lbl_s_presso".tr, style: CustomTextStyles.headlineLargeBlack900)), SizedBox(height: 29.v), CustomImageView(imagePath: ImageConstant.imgRectangle105112x180, height: 112.v, width: 180.h, radius: BorderRadius.circular(11.h), alignment: Alignment.center), SizedBox(height: 69.v), Text("lbl_s_presso_std".tr, style: CustomTextStyles.titleLargeBlack900), SizedBox(height: 18.v), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_price_range_starts".tr, style: CustomTextStyles.bodyMediumLight15)), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_4_25_lac".tr, style: theme.textTheme.headlineLarge)), SizedBox(height: 49.v), CustomElevatedButton(height: 30.v, width: 137.h, text: "lbl_car_enquiry".tr, buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular_1, alignment: Alignment.center), SizedBox(height: 5.v)]))])); } 
/// Section Widget
Widget _buildHomeSection(BuildContext context) { return SizedBox(height: 100.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 35.h, bottom: 20.v), child: Text("lbl_home2".tr, style: CustomTextStyles.bodyMediumWhiteA700))), Align(alignment: Alignment.center, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 39.v), decoration: AppDecoration.fillRed, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_home".tr, style: CustomTextStyles.bodyLargeWhiteA700)), Spacer(flex: 56), GestureDetector(onTap: () {onTapTxtFEEDBACK(context);}, child: Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeRegular)), Spacer(flex: 43), Text("lbl_services".tr, style: CustomTextStyles.bodyLargeRegular)])))])); } 
/// Navigates to the feedbacksuggestionScreen when the action is triggered.
onTapTxtFEEDBACK(BuildContext context) { NavigatorService.pushNamed(AppRoutes.feedbacksuggestionScreen, ); } 
 }
