import 'bloc/carspa_bloc.dart';import 'models/carspa_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/core/utils/validation_functions.dart';import 'package:indus_motors/widgets/app_bar/appbar_leading_image.dart';import 'package:indus_motors/widgets/app_bar/appbar_title.dart';import 'package:indus_motors/widgets/app_bar/appbar_trailing_image.dart';import 'package:indus_motors/widgets/app_bar/custom_app_bar.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';import 'package:indus_motors/widgets/custom_icon_button.dart';import 'package:indus_motors/widgets/custom_outlined_button.dart';import 'package:indus_motors/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class CarspaScreen extends StatelessWidget {CarspaScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<CarspaBloc>(create: (context) => CarspaBloc(CarspaState(carspaModelObj: CarspaModel()))..add(CarspaInitialEvent()), child: CarspaScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 11.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 91.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 10.v), child: CustomIconButton(height: 42.adaptSize, width: 42.adaptSize, onTap: () {onTapBtnIconsBackButtonThirty(context);}, child: CustomImageView(imagePath: ImageConstant.imgIcons8BackButton30))), CustomOutlinedButton(width: 161.h, text: "msg_complete_car_spa2".tr, margin: EdgeInsets.only(left: 48.h, top: 14.v))]))), SizedBox(height: 27.v), CustomImageView(imagePath: ImageConstant.imgWashingJpg500x5001, height: 181.v, width: 311.h, radius: BorderRadius.circular(40.h)), SizedBox(height: 33.v), _buildNameSection(context), SizedBox(height: 16.v), _buildRegisterNoSection(context), SizedBox(height: 64.v), CustomElevatedButton(width: 131.h, text: "lbl_submit".tr, buttonStyle: CustomButtonStyles.fillRed1, onPressed: () {onTapSUBMIT(context);}), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgHome, margin: EdgeInsets.only(left: 30.h, top: 45.v, bottom: 32.v)), centerTitle: true, title: AppbarTitle(text: "lbl_indus_motors2".tr, margin: EdgeInsets.only(top: 49.v, bottom: 25.v)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgEllipse15, margin: EdgeInsets.fromLTRB(19.h, 30.v, 19.h, 31.v))], styleType: Style.bgStyle_4); } 
/// Section Widget
Widget _buildNameSection(BuildContext context) { return Container(margin: EdgeInsets.only(right: 10.h), padding: EdgeInsets.symmetric(horizontal: 31.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 40.h), child: Text("lbl_car_model".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 22.h), child: BlocSelector<CarspaBloc, CarspaState, TextEditingController?>(selector: (state) => state.nameController, builder: (context, nameController) {return CustomTextFormField(controller: nameController, hintText: "msg_enter_your_car_name".tr, alignment: Alignment.centerRight, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}))])); } 
/// Section Widget
Widget _buildRegisterNoSection(BuildContext context) { return Container(margin: EdgeInsets.only(right: 10.h), padding: EdgeInsets.symmetric(horizontal: 31.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 40.h), child: Text("lbl_register_no".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 22.h), child: BlocSelector<CarspaBloc, CarspaState, TextEditingController?>(selector: (state) => state.registerNoPlaceholderController, builder: (context, registerNoPlaceholderController) {return CustomTextFormField(controller: registerNoPlaceholderController, hintText: "msg_enter_your_register".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.number, alignment: Alignment.centerRight, validator: (value) {if (!isNumeric(value)) {return "err_msg_please_enter_valid_number".tr;} return null;});}))])); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapBtnIconsBackButtonThirty(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
/// Navigates to the submittedsuccessfullyScreen when the action is triggered.
onTapSUBMIT(BuildContext context) { NavigatorService.pushNamed(AppRoutes.submittedsuccessfullyScreen, ); } 
 }
