import 'bloc/selectgnrlsrv_bloc.dart';import 'models/selectgnrlsrv_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/core/utils/validation_functions.dart';import 'package:indus_motors/widgets/app_bar/appbar_leading_image.dart';import 'package:indus_motors/widgets/app_bar/appbar_title.dart';import 'package:indus_motors/widgets/app_bar/appbar_trailing_image.dart';import 'package:indus_motors/widgets/app_bar/custom_app_bar.dart';import 'package:indus_motors/widgets/custom_drop_down.dart';import 'package:indus_motors/widgets/custom_icon_button.dart';import 'package:indus_motors/widgets/custom_outlined_button.dart';import 'package:indus_motors/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SelectgnrlsrvScreen extends StatelessWidget {SelectgnrlsrvScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<SelectgnrlsrvBloc>(create: (context) => SelectgnrlsrvBloc(SelectgnrlsrvState(selectgnrlsrvModelObj: SelectgnrlsrvModel()))..add(SelectgnrlsrvInitialEvent()), child: SelectgnrlsrvScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 3.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 80.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 8.v), child: CustomIconButton(height: 42.adaptSize, width: 42.adaptSize, onTap: () {onTapBtnIconsBackButtonThirty(context);}, child: CustomImageView(imagePath: ImageConstant.imgIcons8BackButton30))), CustomOutlinedButton(height: 35.v, width: 166.h, text: "lbl_general_service2".tr, margin: EdgeInsets.only(left: 38.h, top: 15.v))]))), SizedBox(height: 34.v), CustomImageView(imagePath: ImageConstant.imgGeneralService, height: 201.v, width: 312.h, radius: BorderRadius.circular(41.h)), SizedBox(height: 17.v), _buildCarDetails(context), SizedBox(height: 16.v), _buildRegisterNumber(context), SizedBox(height: 16.v), _buildTypeOfService(context), SizedBox(height: 9.v), Align(alignment: Alignment.centerRight, child: Container(width: 160.h, margin: EdgeInsets.only(left: 106.h, right: 60.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 17.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, children: [Align(alignment: Alignment.centerLeft, child: GestureDetector(onTap: () {onTapTxtOilChange(context);}, child: Padding(padding: EdgeInsets.only(left: 13.h), child: Text("lbl_oil_change".tr, style: CustomTextStyles.bodyMediumLight_1)))), SizedBox(height: 11.v), GestureDetector(onTap: () {onTapTxtFreePickDrop(context);}, child: Padding(padding: EdgeInsets.only(right: 4.h), child: Text("lbl_free_pick_drop".tr, style: CustomTextStyles.bodyMediumLight_1))), SizedBox(height: 11.v), Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapTxtBodyCheckup(context);}, child: Text("lbl_body_checkup".tr, style: CustomTextStyles.bodyMediumLight_1))), SizedBox(height: 14.v), GestureDetector(onTap: () {onTapTxtPeriodicService(context);}, child: Text("msg_periodic_service".tr, style: CustomTextStyles.bodyMediumLight_1)), SizedBox(height: 6.v)]))), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgHome, margin: EdgeInsets.only(left: 30.h, top: 45.v, bottom: 32.v)), centerTitle: true, title: AppbarTitle(text: "lbl_indus_motors2".tr, margin: EdgeInsets.only(top: 49.v, bottom: 25.v)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgEllipse15, margin: EdgeInsets.fromLTRB(19.h, 30.v, 19.h, 31.v))], styleType: Style.bgStyle_8); } 
/// Section Widget
Widget _buildCarDetails(BuildContext context) { return Container(margin: EdgeInsets.only(right: 7.h), padding: EdgeInsets.symmetric(horizontal: 18.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 18.h), child: Text("lbl_car_model".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(right: 35.h), child: BlocSelector<SelectgnrlsrvBloc, SelectgnrlsrvState, TextEditingController?>(selector: (state) => state.nameController, builder: (context, nameController) {return CustomTextFormField(controller: nameController, hintText: "msg_enter_your_car_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}))])); } 
/// Section Widget
Widget _buildRegisterNumber(BuildContext context) { return Container(margin: EdgeInsets.only(right: 7.h), padding: EdgeInsets.symmetric(horizontal: 18.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 18.h), child: Text("lbl_register_no".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(right: 35.h), child: BlocSelector<SelectgnrlsrvBloc, SelectgnrlsrvState, TextEditingController?>(selector: (state) => state.registerNumberController, builder: (context, registerNumberController) {return CustomTextFormField(controller: registerNumberController, hintText: "msg_enter_your_register".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.number, validator: (value) {if (!isNumeric(value)) {return "err_msg_please_enter_valid_number".tr;} return null;});}))])); } 
/// Section Widget
Widget _buildTypeOfService(BuildContext context) { return Container(margin: EdgeInsets.only(right: 7.h), padding: EdgeInsets.symmetric(horizontal: 18.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 21.h), child: Text("lbl_type_of_service".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(right: 35.h), child: BlocSelector<SelectgnrlsrvBloc, SelectgnrlsrvState, SelectgnrlsrvModel?>(selector: (state) => state.selectgnrlsrvModelObj, builder: (context, selectgnrlsrvModelObj) {return CustomDropDown(hintText: "lbl_select".tr, items: selectgnrlsrvModelObj?.dropdownItemList ?? [], onChanged: (value) {context.read<SelectgnrlsrvBloc>().add(ChangeDropDownEvent(value: value));});}))])); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapBtnIconsBackButtonThirty(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
/// Navigates to the gsoilchangeScreen when the action is triggered.
onTapTxtOilChange(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gsoilchangeScreen, ); } 
/// Navigates to the gspickdropScreen when the action is triggered.
onTapTxtFreePickDrop(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gspickdropScreen, ); } 
/// Navigates to the gsbodycheckupScreen when the action is triggered.
onTapTxtBodyCheckup(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gsbodycheckupScreen, ); } 
/// Navigates to the gsperoidiccheckupScreen when the action is triggered.
onTapTxtPeriodicService(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gsperoidiccheckupScreen, ); } 
 }
