import 'bloc/invicto_bloc.dart';import 'models/invicto_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/widgets/custom_elevated_button.dart';class InvictoPage extends StatefulWidget {const InvictoPage({Key? key}) : super(key: key);

@override InvictoPageState createState() =>  InvictoPageState();

static Widget builder(BuildContext context) { return BlocProvider<InvictoBloc>(create: (context) => InvictoBloc(InvictoState(invictoModelObj: InvictoModel()))..add(InvictoInitialEvent()), child: InvictoPage()); } 
 }
class InvictoPageState extends State<InvictoPage> with  AutomaticKeepAliveClientMixin<InvictoPage> {@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return BlocBuilder<InvictoBloc, InvictoState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, decoration: AppDecoration.fillWhiteA, child: Column(children: [SizedBox(height: 19.v), Column(children: [CustomElevatedButton(height: 25.v, width: 71.h, text: "lbl_back".tr, margin: EdgeInsets.only(left: 28.h), buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular, alignment: Alignment.centerLeft), SizedBox(height: 20.v), Container(width: 315.h, margin: EdgeInsets.symmetric(horizontal: 22.h), padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 12.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Align(alignment: Alignment.center, child: Text("lbl_invicto".tr, style: CustomTextStyles.headlineLargeBlack900)), SizedBox(height: 40.v), CustomImageView(imagePath: ImageConstant.imgRectangle100, height: 95.v, width: 148.h, radius: BorderRadius.circular(11.h), alignment: Alignment.center), SizedBox(height: 48.v), Container(width: 237.h, margin: EdgeInsets.only(right: 16.h), child: Text("msg_invicto_stong_hybrid_zeta".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleLargeBlack900)), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("msg_price_range_starts".tr, style: CustomTextStyles.bodyMediumLight15)), SizedBox(height: 10.v), Text("lbl_24_79_lac".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 49.v), CustomElevatedButton(height: 30.v, width: 137.h, text: "lbl_car_enquiry".tr, buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700Regular_1, alignment: Alignment.center)])), SizedBox(height: 49.v), _buildHomeRow(context)])]))));}); } 
/// Section Widget
Widget _buildHomeRow(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 39.v), decoration: AppDecoration.fillRed, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_home".tr, style: CustomTextStyles.bodyLargeWhiteA700)), Spacer(flex: 56), GestureDetector(onTap: () {onTapTxtFEEDBACK(context);}, child: Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeRegular)), Spacer(flex: 43), GestureDetector(onTap: () {onTapTxtSERVICES(context);}, child: Text("lbl_services".tr, style: CustomTextStyles.bodyLargeRegular))])); } 
/// Navigates to the feedbacksuggestionScreen when the action is triggered.
onTapTxtFEEDBACK(BuildContext context) { NavigatorService.pushNamed(AppRoutes.feedbacksuggestionScreen, ); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapTxtSERVICES(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
 }
