import 'bloc/submittedsuccessfully_bloc.dart';import 'models/submittedsuccessfully_model.dart';import 'package:flutter/material.dart';import 'package:indus_motors/core/app_export.dart';import 'package:indus_motors/widgets/app_bar/appbar_leading_image.dart';import 'package:indus_motors/widgets/app_bar/appbar_title.dart';import 'package:indus_motors/widgets/app_bar/appbar_trailing_image.dart';import 'package:indus_motors/widgets/app_bar/custom_app_bar.dart';class SubmittedsuccessfullyScreen extends StatelessWidget {const SubmittedsuccessfullyScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SubmittedsuccessfullyBloc>(create: (context) => SubmittedsuccessfullyBloc(SubmittedsuccessfullyState(submittedsuccessfullyModelObj: SubmittedsuccessfullyModel()))..add(SubmittedsuccessfullyInitialEvent()), child: SubmittedsuccessfullyScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<SubmittedsuccessfullyBloc, SubmittedsuccessfullyState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 38.h, top: 241.v, right: 38.h), child: Column(children: [Text("msg_submitted_successfully".tr, style: CustomTextStyles.headlineSmallBlack900Regular), SizedBox(height: 10.v), Text("msg_thanks_visit_again".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 5.v)])), bottomNavigationBar: _buildFiftyEight(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgHome, margin: EdgeInsets.only(left: 30.h, top: 45.v, bottom: 32.v)), centerTitle: true, title: AppbarTitle(text: "lbl_indus_motors2".tr, margin: EdgeInsets.only(top: 49.v, bottom: 25.v)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgEllipse15, margin: EdgeInsets.fromLTRB(19.h, 30.v, 19.h, 31.v))], styleType: Style.bgStyle_7); } 
/// Section Widget
Widget _buildFiftyEight(BuildContext context) { return Container(margin: EdgeInsets.only(left: 39.h, right: 22.h, bottom: 39.v), decoration: AppDecoration.fillRed, child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [Text("lbl_home".tr, style: CustomTextStyles.bodyLargeRegular), Spacer(flex: 56), Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeWhiteA700), Spacer(flex: 43), GestureDetector(onTap: () {onTapTxtSERVICES(context);}, child: Text("lbl_services".tr, style: CustomTextStyles.bodyLargeRegular))])); } 
/// Navigates to the servicesScreen when the action is triggered.
onTapTxtSERVICES(BuildContext context) { NavigatorService.pushNamed(AppRoutes.servicesScreen, ); } 
 }
